### ISSUE TITLE
Update to Bevy v0.13

### ISSUE THREAD

**Issue by joshuaoco** [yopox/bevy_text_mode#1]
Hello!

I wanted to make this issue to gauge your interest in upgrading the library to Bevy v0.12.1.

I'd quite like to use it on this version, and I'm not familiar at all with the Bevy rendering code so I think I'd have a bit of trouble submitting the PR myself, but if you're definitely not interested in upgrading yourself (which I totally understand, the moving target is frustrating!), then I would try and take a crack at it.

From my "increase the version and try to compile" test, the main changes seem to be:

- New asset system (impacts Handles I think) - https://bevyengine.org/learn/migration-guides/0.11-0.12/#bevy-asset-v2
- Removal/change of how items are batched
  This is the main one I think I'd struggle with, the relevant PR is [here](https://github.com/bevyengine/bevy/pull/9236) but it's missing from the migration guide as noted [here](https://github.com/bevyengine/bevy-website/issues/811)
  
  
  
Anyway, thanks for the library!

**Comment by yopox** [comment]
Hi, I have started the migration in the branch `0.12`. The plugin runs, but there is still a problem with vertices. UVs have also changed so rotation is yet to be implemented. (the plugin is a copy of `bevy_sprite::render::mod.rs` with 2 colors, alpha and rotation instead of just a tint color)

![CleanShot 2024-01-22 at 10 36 16@2x](https://github.com/yopox/bevy_text_mode/assets/8440079/9e292046-1b4a-4f51-9185-44b21c7458b3)
